### ISSUE TITLE
Support erb format on yaml file.

### ISSUE THREAD

**Issue by treby** [fetaro/rbatch#4]
I tried to use RBatch on production and encountered a little problem; I can't use environment variables as `RBatch.config` variable.

Of cause, we can use them on our script by accessing `ENV` directly. But I don't think it's a good idea because multiple ways to access configuration may confuse us.

And some frameworks support environment variable for config(yaml) file by parsing with `erb` (example below).

```
:
consumer_key: <%= ENV['CONSUMER_KEY'] %>
consumer_secret: <%= ENV['CONSUMER_SECRET'] %>
:
```

I think it's better to support `erb` format for yaml file.

Let me know what you think. And I'm happy to open pull request if this idea makes sense for us.
Thanks!

**Comment by fetaro** [comment]
Thank you for using RBatch! 
I think your idea is great.
Because the implementation seems to be easy, I will do it in a day or two.
You do not need to make a pull request.
Thanks!

**Comment by treby** [comment]
I see, thanks :smiley_cat:

**Comment by fetaro** [comment]
I make it at v2.5.0.
Please rename your config file from `xxx.yaml` into `xxx.yaml.erb` .

**Comment by treby** [comment]
I did `bundle update` and used it.
This is it! Awesome :beers:
